//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasosTotalizadores.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasosTotalizadores.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You should start playing the movie now.
        /// </summary>
        internal static string AlertMessageMovieShouldPlayMovieNow {
            get {
                return ResourceManager.GetString("AlertMessageMovieShouldPlayMovieNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movie Tapped!.
        /// </summary>
        internal static string AlertTitleMovieTapped {
            get {
                return ResourceManager.GetString("AlertTitleMovieTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enjoy it now!.
        /// </summary>
        internal static string BannerBodyEnjoyItNow {
            get {
                return ResourceManager.GetString("BannerBodyEnjoyItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 25% discount.
        /// </summary>
        internal static string BannerTitle25DiscOff {
            get {
                return ResourceManager.GetString("BannerTitle25DiscOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Comment.
        /// </summary>
        internal static string ButtonAddComment {
            get {
                return ResourceManager.GetString("ButtonAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to cart.
        /// </summary>
        internal static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already a user? Login now.
        /// </summary>
        internal static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse our samples.
        /// </summary>
        internal static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string ButtonConfiguracion {
            get {
                return ResourceManager.GetString("ButtonConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Account.
        /// </summary>
        internal static string ButtonDeleteAccount {
            get {
                return ResourceManager.GetString("ButtonDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More.
        /// </summary>
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonOtros.
        /// </summary>
        internal static string ButtonOtros {
            get {
                return ResourceManager.GetString("ButtonOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Movie.
        /// </summary>
        internal static string ButtonPlayMovie {
            get {
                return ResourceManager.GetString("ButtonPlayMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primary Action.
        /// </summary>
        internal static string ButtonPrimaryAction {
            get {
                return ResourceManager.GetString("ButtonPrimaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secondary Action.
        /// </summary>
        internal static string ButtonSecondaryAction {
            get {
                return ResourceManager.GetString("ButtonSecondaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See our walkthrough.
        /// </summary>
        internal static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I&apos;m an Editor 
        ///and I love multiple lines! ;).
        /// </summary>
        internal static string EditorSampleText {
            get {
                return ResourceManager.GetString("EditorSampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        internal static string EntryCellPlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("EntryCellPlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a robert.stainford@uxdivers.com.
        /// </summary>
        internal static string EntryCellSampleEmail {
            get {
                return ResourceManager.GetString("EntryCellSampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a valid e-mail.
        /// </summary>
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 50 days logged in.
        /// </summary>
        internal static string ImageCellDetailDaysLoggedIn {
            get {
                return ResourceManager.GetString("ImageCellDetailDaysLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VS Studio PartnerWe are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        internal static string LabelAboutUsText {
            get {
                return ResourceManager.GetString("LabelAboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ActivityIndicators.
        /// </summary>
        internal static string LabelActivityIndicators {
            get {
                return ResourceManager.GetString("LabelActivityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artina Buttons.
        /// </summary>
        internal static string LabelArtinaButtons {
            get {
                return ResourceManager.GetString("LabelArtinaButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artina Entry.
        /// </summary>
        internal static string LabelArtinaEntry {
            get {
                return ResourceManager.GetString("LabelArtinaEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Badge.
        /// </summary>
        internal static string LabelBadge {
            get {
                return ResourceManager.GetString("LabelBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BrandBlock.
        /// </summary>
        internal static string LabelBrandBlock {
            get {
                return ResourceManager.GetString("LabelBrandBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buttons.
        /// </summary>
        internal static string LabelButtons {
            get {
                return ResourceManager.GetString("LabelButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CircleImages.
        /// </summary>
        internal static string LabelCircleImages {
            get {
                return ResourceManager.GetString("LabelCircleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Image Cache.
        /// </summary>
        internal static string LabelClearImageCache {
            get {
                return ResourceManager.GetString("LabelClearImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        internal static string LabelCredits {
            get {
                return ResourceManager.GetString("LabelCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note the Menu displayed on top ;).
        /// </summary>
        internal static string LabelCustomavBarNoteMenu {
            get {
                return ResourceManager.GetString("LabelCustomavBarNoteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom NavBar.
        /// </summary>
        internal static string LabelCustomNavBar {
            get {
                return ResourceManager.GetString("LabelCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The NavBar on this page is totally custom which means you could add as many icons as you need and combine it with other views such as badges, etc..
        /// </summary>
        internal static string LabelCustomNavBarText {
            get {
                return ResourceManager.GetString("LabelCustomNavBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Global issues.
        /// </summary>
        internal static string LabelDisplayGlobalIssues {
            get {
                return ResourceManager.GetString("LabelDisplayGlobalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entries And Editors.
        /// </summary>
        internal static string LabelEntriesAndEditors {
            get {
                return ResourceManager.GetString("LabelEntriesAndEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t worry type your email here and we will recover it for you..
        /// </summary>
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frames.
        /// </summary>
        internal static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListView and SearchBar.
        /// </summary>
        internal static string LabelListViewAndSearchBar {
            get {
                return ResourceManager.GetString("LabelListViewAndSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos Totalizadores.
        /// </summary>
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need custom animations?.
        /// </summary>
        internal static string LabelNeedCustomAnimations {
            get {
                return ResourceManager.GetString("LabelNeedCustomAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Or connect with.
        /// </summary>
        internal static string LabelOrConnectWith {
            get {
                return ResourceManager.GetString("LabelOrConnectWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our Products.
        /// </summary>
        internal static string LabelOurProducts {
            get {
                return ResourceManager.GetString("LabelOurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial UI Kit and Gorilla Player for Xamarin.Forms
        ///had been helping developers build better and good looking apps faster since 2015.
        ///Stay tunned we have more surprises coming soon….
        /// </summary>
        internal static string LabelOurProductsLongText {
            get {
                return ResourceManager.GetString("LabelOurProductsLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passion driven designer and developer. Frustrated musician and father of two..
        /// </summary>
        internal static string LabelPassionDrivenDesigner {
            get {
                return ResourceManager.GetString("LabelPassionDrivenDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photography is my passion. Black and white is the way I see the world..
        /// </summary>
        internal static string LabelPhotographyIsMyPassion {
            get {
                return ResourceManager.GetString("LabelPhotographyIsMyPassion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pickers.
        /// </summary>
        internal static string LabelPickers {
            get {
                return ResourceManager.GetString("LabelPickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProgressBars.
        /// </summary>
        internal static string LabelProgressBars {
            get {
                return ResourceManager.GetString("LabelProgressBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register now.
        /// </summary>
        internal static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register now and enjoy the pleasures of the demo..
        /// </summary>
        internal static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Password.
        /// </summary>
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RoundedLabel.
        /// </summary>
        internal static string LabelRoundedLabel {
            get {
                return ResourceManager.GetString("LabelRoundedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sliders.
        /// </summary>
        internal static string LabelSliders {
            get {
                return ResourceManager.GetString("LabelSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special thanks.
        /// </summary>
        internal static string LabelSpecialThanks {
            get {
                return ResourceManager.GetString("LabelSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switches.
        /// </summary>
        internal static string LabelSwitches {
            get {
                return ResourceManager.GetString("LabelSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take your app to the next level with Grial UI Kit..
        /// </summary>
        internal static string LabelTakeYourAppToNextLevel {
            get {
                return ResourceManager.GetString("LabelTakeYourAppToNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s nothing here my friend :).
        /// </summary>
        internal static string LabelThereIsNothingHere {
            get {
                return ResourceManager.GetString("LabelThereIsNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is a frame containing a Label control.
        /// </summary>
        internal static string LabelThisIsAFrameDescription {
            get {
                return ResourceManager.GetString("LabelThisIsAFrameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usa sus credenciales para iniciar sesion.
        /// </summary>
        internal static string LabelUseCredentialsToLogin {
            get {
                return ResourceManager.GetString("LabelUseCredentialsToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I like my toast done on one side..
        /// </summary>
        internal static string LabelUserDescriptionVariant {
            get {
                return ResourceManager.GetString("LabelUserDescriptionVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation Entry Error Style.
        /// </summary>
        internal static string LabelValidationEntryErrorStyle {
            get {
                return ResourceManager.GetString("LabelValidationEntryErrorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VS Studio Partner.
        /// </summary>
        internal static string LabelVisualStudioPartner {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a As partners of the greatest IDE ever, we are commited to deliver high quality products that really help devs to achieve their best..
        /// </summary>
        internal static string LabelVisualStudioPartnerLongText {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartnerLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        internal static string LabelWeAreATeamOfPassionate {
            get {
                return ResourceManager.GetString("LabelWeAreATeamOfPassionate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos Totalizadores.
        /// </summary>
        internal static string LabelWelcomeToGrialStarter {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Grial Starter. You are all setup and ready to rock!.
        /// </summary>
        internal static string LabelWelcomeToGrialStarterDescription {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes! Grial UI Kit now supports Lottie Animations out of the box..
        /// </summary>
        internal static string LabelYesGrialSupportsLottie {
            get {
                return ResourceManager.GetString("LabelYesGrialSupportsLottie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edenorte.
        /// </summary>
        internal static string LoginPageTitulo {
            get {
                return ResourceManager.GetString("LoginPageTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icons Dashboard.
        /// </summary>
        internal static string PageMenuTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageMenuTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generic About Page.
        /// </summary>
        internal static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animation.
        /// </summary>
        internal static string PageTitleAnimation {
            get {
                return ResourceManager.GetString("PageTitleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles Classic View.
        /// </summary>
        internal static string PageTitleArticleClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticleClassicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles List.
        /// </summary>
        internal static string PageTitleArticleList {
            get {
                return ResourceManager.GetString("PageTitleArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles Feed.
        /// </summary>
        internal static string PageTitleArticlesFeed {
            get {
                return ResourceManager.GetString("PageTitleArticlesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles List Variant.
        /// </summary>
        internal static string PageTitleArticlesListVariant {
            get {
                return ResourceManager.GetString("PageTitleArticlesListVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article View.
        /// </summary>
        internal static string PageTitleArticleView {
            get {
                return ResourceManager.GetString("PageTitleArticleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cards List.
        /// </summary>
        internal static string PageTitleCardsList {
            get {
                return ResourceManager.GetString("PageTitleCardsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories List Flat.
        /// </summary>
        internal static string PageTitleCategoriesListFlat {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icon Categories.
        /// </summary>
        internal static string PageTitleCategoriesListWithIcons {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListWithIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Categories.
        /// </summary>
        internal static string PageTitleCategoryListImages {
            get {
                return ResourceManager.GetString("PageTitleCategoryListImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat Messages List.
        /// </summary>
        internal static string PageTitleChatMessageList {
            get {
                return ResourceManager.GetString("PageTitleChatMessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat Timeline.
        /// </summary>
        internal static string PageTitleChatTimeLine {
            get {
                return ResourceManager.GetString("PageTitleChatTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial Common Views.
        /// </summary>
        internal static string PageTitleCommonViews {
            get {
                return ResourceManager.GetString("PageTitleCommonViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Activity Indicator.
        /// </summary>
        internal static string PageTitleCustomActivityIndicator {
            get {
                return ResourceManager.GetString("PageTitleCustomActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom NavBar.
        /// </summary>
        internal static string PageTitleCustomNavBar {
            get {
                return ResourceManager.GetString("PageTitleCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Renderers.
        /// </summary>
        internal static string PageTitleCustomRenderers {
            get {
                return ResourceManager.GetString("PageTitleCustomRenderers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Settings Page.
        /// </summary>
        internal static string PageTitleCustomSettings {
            get {
                return ResourceManager.GetString("PageTitleCustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard Cards.
        /// </summary>
        internal static string PageTitleDashboardCards {
            get {
                return ResourceManager.GetString("PageTitleDashboardCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flat Dashboard.
        /// </summary>
        internal static string PageTitleDashboardFlat {
            get {
                return ResourceManager.GetString("PageTitleDashboardFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string PageTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard Multiple Scroll.
        /// </summary>
        internal static string PageTitleDashboardMultipleScroll {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple Tiles.
        /// </summary>
        internal static string PageTitleDashboardMultipleTiles {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard Scrollable.
        /// </summary>
        internal static string PageTitleDashboardScrollable {
            get {
                return ResourceManager.GetString("PageTitleDashboardScrollable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Images Dashboard.
        /// </summary>
        internal static string PageTitleDashboardWithImages {
            get {
                return ResourceManager.GetString("PageTitleDashboardWithImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document Timeline.
        /// </summary>
        internal static string PageTitleDocumentTimeline {
            get {
                return ResourceManager.GetString("PageTitleDocumentTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty State.
        /// </summary>
        internal static string PageTitleEmptyState {
            get {
                return ResourceManager.GetString("PageTitleEmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Front Page News.
        /// </summary>
        internal static string PageTitleFrontPageNews {
            get {
                return ResourceManager.GetString("PageTitleFrontPageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        internal static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messages.
        /// </summary>
        internal static string PageTitleMessages {
            get {
                return ResourceManager.GetString("PageTitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movie Selection.
        /// </summary>
        internal static string PageTitleMovieSelection {
            get {
                return ResourceManager.GetString("PageTitleMovieSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Native Controls.
        /// </summary>
        internal static string PageTitleNativeControls {
            get {
                return ResourceManager.GetString("PageTitleNativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Recovery.
        /// </summary>
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Grid.
        /// </summary>
        internal static string PageTitleProductGrid {
            get {
                return ResourceManager.GetString("PageTitleProductGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Grid Variant.
        /// </summary>
        internal static string PageTitleProductGridVariant {
            get {
                return ResourceManager.GetString("PageTitleProductGridVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Order.
        /// </summary>
        internal static string PageTitleProductOrder {
            get {
                return ResourceManager.GetString("PageTitleProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Catalog.
        /// </summary>
        internal static string PageTitleProductsCatalog {
            get {
                return ResourceManager.GetString("PageTitleProductsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent Chat List.
        /// </summary>
        internal static string PageTitleRecentChatList {
            get {
                return ResourceManager.GetString("PageTitleRecentChatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsive Helpers.
        /// </summary>
        internal static string PageTitleResponsiveHelpers {
            get {
                return ResourceManager.GetString("PageTitleResponsiveHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings Page.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        internal static string PageTitleSignup {
            get {
                return ResourceManager.GetString("PageTitleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple Login.
        /// </summary>
        internal static string PageTitleSimpleLogin {
            get {
                return ResourceManager.GetString("PageTitleSimpleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple Sign Up.
        /// </summary>
        internal static string PageTitleSimpleSignup {
            get {
                return ResourceManager.GetString("PageTitleSimpleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social Variant.
        /// </summary>
        internal static string PageTitleSocialVariant {
            get {
                return ResourceManager.GetString("PageTitleSocialVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información visita.
        /// </summary>
        internal static string PageTitleTabbedPage {
            get {
                return ResourceManager.GetString("PageTitleTabbedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial TabControl MenuItems Page.
        /// </summary>
        internal static string PageTitleTabControl {
            get {
                return ResourceManager.GetString("PageTitleTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme Icons Preview.
        /// </summary>
        internal static string PageTitleThemeFontIcons {
            get {
                return ResourceManager.GetString("PageTitleThemeFontIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial Themes Preview.
        /// </summary>
        internal static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeline.
        /// </summary>
        internal static string PageTitleTimeline {
            get {
                return ResourceManager.GetString("PageTitleTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        internal static string PageTitleTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WebView.
        /// </summary>
        internal static string PageTitleWebview {
            get {
                return ResourceManager.GetString("PageTitleWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome Page.
        /// </summary>
        internal static string PageTitleWelcome {
            get {
                return ResourceManager.GetString("PageTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome Starter.
        /// </summary>
        internal static string PageTitleWelcomeStarter {
            get {
                return ResourceManager.GetString("PageTitleWelcomeStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I&apos;m a Picker!.
        /// </summary>
        internal static string PickerTitleSample {
            get {
                return ResourceManager.GetString("PickerTitleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAST.
        /// </summary>
        internal static string RoundedLabelCast {
            get {
                return ResourceManager.GetString("RoundedLabelCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECTOR.
        /// </summary>
        internal static string RoundedLabelDirector {
            get {
                return ResourceManager.GetString("RoundedLabelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial Rounded Label MenuItems.
        /// </summary>
        internal static string RoundedLabelTextSample {
            get {
                return ResourceManager.GetString("RoundedLabelTextSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial Movies.
        /// </summary>
        internal static string SampleDashboardGrialMovies {
            get {
                return ResourceManager.GetString("SampleDashboardGrialMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Carousel.
        /// </summary>
        internal static string SampleProductCarousel {
            get {
                return ResourceManager.GetString("SampleProductCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product FullScreen.
        /// </summary>
        internal static string SampleProductFullscreen {
            get {
                return ResourceManager.GetString("SampleProductFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Item View.
        /// </summary>
        internal static string SampleProductItemView {
            get {
                return ResourceManager.GetString("SampleProductItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Root Page.
        /// </summary>
        internal static string SampleTitleRootPage {
            get {
                return ResourceManager.GetString("SampleTitleRootPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demo Settings.
        /// </summary>
        internal static string SampleTitleThemeDemoSettings {
            get {
                return ResourceManager.GetString("SampleTitleThemeDemoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkthrough.
        /// </summary>
        internal static string SampleTitleWalkthrough {
            get {
                return ResourceManager.GetString("SampleTitleWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkthrough Flat.
        /// </summary>
        internal static string SampleTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkthrough Variant.
        /// </summary>
        internal static string SampleTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Profile.
        /// </summary>
        internal static string SampleUserProfile {
            get {
                return ResourceManager.GetString("SampleUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for a name.
        /// </summary>
        internal static string SearchBarPlaceholderSearchForAName {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderSearchForAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string StringAddress {
            get {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address Line 1.
        /// </summary>
        internal static string StringAddress1 {
            get {
                return ResourceManager.GetString("StringAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address Line 2.
        /// </summary>
        internal static string StringAddress2 {
            get {
                return ResourceManager.GetString("StringAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance.
        /// </summary>
        internal static string StringBalance {
            get {
                return ResourceManager.GetString("StringBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batman&apos;s choice.
        /// </summary>
        internal static string StringBatmanChoice {
            get {
                return ResourceManager.GetString("StringBatmanChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use sus credenciales para iniciar sesión.
        /// </summary>
        internal static string StringBienvenido {
            get {
                return ResourceManager.GetString("StringBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        internal static string StringBuy {
            get {
                return ResourceManager.GetString("StringBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Call the experts.
        /// </summary>
        internal static string StringCallTheExperts {
            get {
                return ResourceManager.GetString("StringCallTheExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t reach your current location.
        /// </summary>
        internal static string StringCantReachLocation {
            get {
                return ResourceManager.GetString("StringCantReachLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card Number.
        /// </summary>
        internal static string StringCardNumber {
            get {
                return ResourceManager.GetString("StringCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles.
        /// </summary>
        internal static string StringCategoryArticles {
            get {
                return ResourceManager.GetString("StringCategoryArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboards.
        /// </summary>
        internal static string StringCategoryDashboards {
            get {
                return ResourceManager.GetString("StringCategoryDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ECommerce.
        /// </summary>
        internal static string StringCategoryECommerce {
            get {
                return ResourceManager.GetString("StringCategoryECommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logins.
        /// </summary>
        internal static string StringCategoryLogins {
            get {
                return ResourceManager.GetString("StringCategoryLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messages.
        /// </summary>
        internal static string StringCategoryMessages {
            get {
                return ResourceManager.GetString("StringCategoryMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigation.
        /// </summary>
        internal static string StringCategoryNavigation {
            get {
                return ResourceManager.GetString("StringCategoryNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        internal static string StringCategoryTheme {
            get {
                return ResourceManager.GetString("StringCategoryTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkthroughs.
        /// </summary>
        internal static string StringCategoryWalkthroughs {
            get {
                return ResourceManager.GetString("StringCategoryWalkthroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string StringCity {
            get {
                return ResourceManager.GetString("StringCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clare Japi.
        /// </summary>
        internal static string StringClareJapi {
            get {
                return ResourceManager.GetString("StringClareJapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string StringCliente {
            get {
                return ResourceManager.GetString("StringCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ,.
        /// </summary>
        internal static string StringColon {
            get {
                return ResourceManager.GetString("StringColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare.
        /// </summary>
        internal static string StringCompare {
            get {
                return ResourceManager.GetString("StringCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        internal static string StringConfiguracion {
            get {
                return ResourceManager.GetString("StringConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect Your Account.
        /// </summary>
        internal static string StringConnectYourAccount {
            get {
                return ResourceManager.GetString("StringConnectYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros consumos.
        /// </summary>
        internal static string StringConsumo {
            get {
                return ResourceManager.GetString("StringConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        internal static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Context Action Tapped.
        /// </summary>
        internal static string StringContextActionTapped {
            get {
                return ResourceManager.GetString("StringContextActionTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        internal static string StringCountry {
            get {
                return ResourceManager.GetString("StringCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom ?.
        /// </summary>
        internal static string StringCustom {
            get {
                return ResourceManager.GetString("StringCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVC.
        /// </summary>
        internal static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark.
        /// </summary>
        internal static string StringDark {
            get {
                return ResourceManager.GetString("StringDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DarkTheme.
        /// </summary>
        internal static string StringDarkTheme {
            get {
                return ResourceManager.GetString("StringDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        internal static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enterprise.
        /// </summary>
        internal static string StringEnterprise {
            get {
                return ResourceManager.GetString("StringEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EnterpriseTheme.
        /// </summary>
        internal static string StringEnterpriseTheme {
            get {
                return ResourceManager.GetString("StringEnterpriseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration Date.
        /// </summary>
        internal static string StringExpirationDate {
            get {
                return ResourceManager.GetString("StringExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extra soft UI flavor.
        /// </summary>
        internal static string StringExtraSoftUIFlavor {
            get {
                return ResourceManager.GetString("StringExtraSoftUIFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook.
        /// </summary>
        internal static string StringFacebook {
            get {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish!.
        /// </summary>
        internal static string StringFinish {
            get {
                return ResourceManager.GetString("StringFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRIENDS.
        /// </summary>
        internal static string StringFriends {
            get {
                return ResourceManager.GetString("StringFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Give us a call.
        /// </summary>
        internal static string StringGiveUsACall {
            get {
                return ResourceManager.GetString("StringGiveUsACall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grial.
        /// </summary>
        internal static string StringGrial {
            get {
                return ResourceManager.GetString("StringGrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icons.
        /// </summary>
        internal static string StringIcons {
            get {
                return ResourceManager.GetString("StringIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impress your boss.
        /// </summary>
        internal static string StringImpressYourBoss {
            get {
                return ResourceManager.GetString("StringImpressYourBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        internal static string StringLight {
            get {
                return ResourceManager.GetString("StringLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LightTheme.
        /// </summary>
        internal static string StringLightTheme {
            get {
                return ResourceManager.GetString("StringLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Linkedin.
        /// </summary>
        internal static string StringLinkedin {
            get {
                return ResourceManager.GetString("StringLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digite el número del medidor.
        /// </summary>
        internal static string StringListadoEntry {
            get {
                return ResourceManager.GetString("StringListadoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message Tapped.
        /// </summary>
        internal static string StringMessageTapped {
            get {
                return ResourceManager.GetString("StringMessageTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More from {0}.
        /// </summary>
        internal static string StringMoreFrom {
            get {
                return ResourceManager.GetString("StringMoreFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW.
        /// </summary>
        internal static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string StringNext {
            get {
                return ResourceManager.GetString("StringNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PHOTOS.
        /// </summary>
        internal static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm your email address.
        /// </summary>
        internal static string StringPleaseConfirmAddress {
            get {
                return ResourceManager.GetString("StringPleaseConfirmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please contact support center.
        /// </summary>
        internal static string StringPleaseContactSupport {
            get {
                return ResourceManager.GetString("StringPleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string StringPrevious {
            get {
                return ResourceManager.GetString("StringPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready made UI&apos;s for Xamarin.Forms..
        /// </summary>
        internal static string StringReadyMadeUIsForXamarin {
            get {
                return ResourceManager.GetString("StringReadyMadeUIsForXamarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Richard Stainford.
        /// </summary>
        internal static string StringRichardStainford {
            get {
                return ResourceManager.GetString("StringRichardStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Robert Stainford.
        /// </summary>
        internal static string StringRobertStainford {
            get {
                return ResourceManager.GetString("StringRobertStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        internal static string StringSaveChanges {
            get {
                return ResourceManager.GetString("StringSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a screens.
        /// </summary>
        internal static string StringScreens {
            get {
                return ResourceManager.GetString("StringScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share.
        /// </summary>
        internal static string StringShare {
            get {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up!.
        /// </summary>
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something wrong here.
        /// </summary>
        internal static string StringSomethingWrongHere {
            get {
                return ResourceManager.GetString("StringSomethingWrongHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You tapped on {0}&apos;s message..
        /// </summary>
        internal static string StringTappedOnAuthorMessage {
            get {
                return ResourceManager.GetString("StringTappedOnAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You tapped on {0} context action..
        /// </summary>
        internal static string StringTappedOnContextAction {
            get {
                return ResourceManager.GetString("StringTappedOnContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos Totalizadores.
        /// </summary>
        internal static string StringTitulo {
            get {
                return ResourceManager.GetString("StringTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de visitas.
        /// </summary>
        internal static string StringTituloPaginaListado {
            get {
                return ResourceManager.GetString("StringTituloPaginaListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totalizador.
        /// </summary>
        internal static string StringTotalizador {
            get {
                return ResourceManager.GetString("StringTotalizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter.
        /// </summary>
        internal static string StringTwitter {
            get {
                return ResourceManager.GetString("StringTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UI.KIT.
        /// </summary>
        internal static string StringUIKIT {
            get {
                return ResourceManager.GetString("StringUIKIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Grial!.
        /// </summary>
        internal static string StringWelcomeToGrial {
            get {
                return ResourceManager.GetString("StringWelcomeToGrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have a new follower.
        /// </summary>
        internal static string StringYouHaveANewFollower {
            get {
                return ResourceManager.GetString("StringYouHaveANewFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have a new message.
        /// </summary>
        internal static string StringYouHaveANewMessage {
            get {
                return ResourceManager.GetString("StringYouHaveANewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Account.
        /// </summary>
        internal static string StringYourAccount {
            get {
                return ResourceManager.GetString("StringYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code.
        /// </summary>
        internal static string StringZipCode {
            get {
                return ResourceManager.GetString("StringZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        internal static string TabItemTextAction {
            get {
                return ResourceManager.GetString("TabItemTextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Android Tab.
        /// </summary>
        internal static string TabItemTextAndroid {
            get {
                return ResourceManager.GetString("TabItemTextAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comedy.
        /// </summary>
        internal static string TabItemTextComedy {
            get {
                return ResourceManager.GetString("TabItemTextComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drama.
        /// </summary>
        internal static string TabItemTextDrama {
            get {
                return ResourceManager.GetString("TabItemTextDrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family.
        /// </summary>
        internal static string TabItemTextFamily {
            get {
                return ResourceManager.GetString("TabItemTextFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heroes.
        /// </summary>
        internal static string TabItemTextHeroes {
            get {
                return ResourceManager.GetString("TabItemTextHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iOS Tab.
        /// </summary>
        internal static string TabItemTextiOS {
            get {
                return ResourceManager.GetString("TabItemTextiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sci Fi.
        /// </summary>
        internal static string TabItemTextSciFi {
            get {
                return ResourceManager.GetString("TabItemTextSciFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UXDIVERS.
        /// </summary>
        internal static string UXDIVERS {
            get {
                return ResourceManager.GetString("UXDIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter required information.
        /// </summary>
        internal static string ValidationErrorEnterRequiredInfo {
            get {
                return ResourceManager.GetString("ValidationErrorEnterRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! This is just a friendly warning.
        /// </summary>
        internal static string ValidationWarningOops {
            get {
                return ResourceManager.GetString("ValidationWarningOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn.
        /// </summary>
        internal static string WalkthroughHeaderLearn {
            get {
                return ResourceManager.GetString("WalkthroughHeaderLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Time.
        /// </summary>
        internal static string WalkthroughHeaderSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughHeaderSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string WalkthroughHeaderWelcome {
            get {
                return ResourceManager.GetString("WalkthroughHeaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn while you do.
        ///Grial has tones of examples for you to play..
        /// </summary>
        internal static string WalkthroughTextLearn {
            get {
                return ResourceManager.GetString("WalkthroughTextLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save countless hours of UI design.
        ///Focus on what you do best..
        /// </summary>
        internal static string WalkthroughTextSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughTextSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To a new world of posibilities,
        ///welcome to Grial UI Kit..
        /// </summary>
        internal static string WalkthroughTextWelcome {
            get {
                return ResourceManager.GetString("WalkthroughTextWelcome", resourceCulture);
            }
        }
    }
}
